# Generated by cpp11: do not edit by hand

zone_database_names_cpp <- function() {
  .Call(`_zones_zone_database_names_cpp`)
}

zones_set_install_cpp <- function(path) {
  invisible(.Call(`_zones_zones_set_install_cpp`, path))
}

zone_database_version_cpp <- function() {
  .Call(`_zones_zone_database_version_cpp`)
}
